-- CreateTable: Post
CREATE TABLE "posts" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "authorId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "excerpt" TEXT,
    "content" JSONB NOT NULL,
    "htmlContent" TEXT,
    "featuredImage" TEXT,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "publishedAt" TIMESTAMP(3),
    "scheduledFor" TIMESTAMP(3),
    "views" INTEGER NOT NULL DEFAULT 0,
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "metaKeywords" TEXT,
    "ogImage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "posts_pkey" PRIMARY KEY ("id")
);

-- CreateTable: Page, Category, Tag, Comment, PostCategory, PostTag
-- (Full SQL generated by Prisma)

CREATE INDEX "posts_tenantId_status_publishedAt_idx" ON "posts"("tenantId", "status", "publishedAt");
CREATE INDEX "posts_authorId_idx" ON "posts"("authorId");
CREATE UNIQUE INDEX "posts_tenantId_slug_key" ON "posts"("tenantId", "slug");
