#!/bin/bash

# ────────────────────────────────────────────────────────────────
# Enterprise SaaS Backend - Automated Setup Script
# One-command setup for complete development environment
# ────────────────────────────────────────────────────────────────

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ─── Helper Functions ─────────────────────────────────────────

print_header() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

generate_secret() {
    openssl rand -base64 32
}

# ─── Main Setup ───────────────────────────────────────────────

print_header "Enterprise SaaS Backend - Setup Wizard"

# Check prerequisites
print_info "Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    print_error "Docker is not installed. Please install Docker first."
    exit 1
fi
print_success "Docker is installed"

if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    print_error "Docker Compose is not installed. Please install Docker Compose first."
    exit 1
fi
print_success "Docker Compose is installed"

# Check if .env already exists
if [ -f .env ]; then
    print_warning ".env file already exists"
    read -p "Do you want to overwrite it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Keeping existing .env file"
        ENV_EXISTS=true
    else
        ENV_EXISTS=false
    fi
else
    ENV_EXISTS=false
fi

# Generate .env file
if [ "$ENV_EXISTS" = false ]; then
    print_header "Step 1: Generating Environment Configuration"

    JWT_SECRET=$(generate_secret)
    DB_PASSWORD=$(openssl rand -base64 16 | tr -d "=+/" | cut -c1-16)
    ADMIN_PASSWORD=$(openssl rand -base64 12 | tr -d "=+/" | cut -c1-12)

    cat > .env << EOF
# ────────────────────────────────────────────────────────────────
# Auto-generated by setup.sh on $(date)
# ────────────────────────────────────────────────────────────────

# ─── Server Configuration ─────────────────────────────────────
PORT=3000
HOST=0.0.0.0
NODE_ENV=development

# ─── Database Configuration ───────────────────────────────────
POSTGRES_DB=enterprise_saas
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_PORT=5432
DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@localhost:5432/enterprise_saas

# ─── JWT Configuration ────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d

# ─── Redis Configuration ──────────────────────────────────────
REDIS_URL=redis://localhost:6379
REDIS_PORT=6379

# ─── File Upload Configuration ────────────────────────────────
UPLOAD_DIR=uploads
MAX_FILE_SIZE=10485760

# ─── Logging Configuration ────────────────────────────────────
LOG_LEVEL=debug

# ─── Admin Credentials (for seeding) ──────────────────────────
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

    print_success "Environment file created (.env)"
    print_info "Database password: ${DB_PASSWORD}"
    print_info "Admin password: ${ADMIN_PASSWORD}"

    # Save credentials to a temporary file
    cat > .setup-credentials.txt << EOF
Enterprise SaaS Backend - Setup Credentials
Generated on: $(date)

Database:
  Host: localhost
  Port: 5432
  Database: enterprise_saas
  Username: postgres
  Password: ${DB_PASSWORD}

Redis:
  Host: localhost
  Port: 6379

Admin User:
  Email: admin@example.com
  Password: ${ADMIN_PASSWORD}

API:
  URL: http://localhost:3000
  Docs: http://localhost:3000/docs
  Health: http://localhost:3000/health

Important: Keep these credentials secure!
This file will be deleted after setup completes.
EOF
fi

# Start Docker services
print_header "Step 2: Starting Docker Services"

print_info "Starting PostgreSQL and Redis..."
docker-compose up -d postgres redis

print_success "Database and cache services started"

# Wait for services to be ready
print_info "Waiting for services to be ready..."
sleep 5

# Check PostgreSQL
MAX_RETRIES=30
RETRY=0
until docker-compose exec -T postgres pg_isready -U postgres > /dev/null 2>&1 || [ $RETRY -eq $MAX_RETRIES ]; do
    print_info "Waiting for PostgreSQL... ($RETRY/$MAX_RETRIES)"
    RETRY=$((RETRY+1))
    sleep 2
done

if [ $RETRY -eq $MAX_RETRIES ]; then
    print_error "PostgreSQL failed to start"
    exit 1
fi
print_success "PostgreSQL is ready"

# Check Redis
if docker-compose exec -T redis redis-cli ping > /dev/null 2>&1; then
    print_success "Redis is ready"
else
    print_warning "Redis is not responding (optional service)"
fi

# Install dependencies (if node_modules doesn't exist)
if [ ! -d "node_modules" ]; then
    print_header "Step 3: Installing Dependencies"
    print_info "Running npm install..."
    npm install
    print_success "Dependencies installed"
else
    print_info "Dependencies already installed (skipping npm install)"
fi

# Generate Prisma Client
print_header "Step 4: Generating Prisma Client"
npx prisma generate
print_success "Prisma client generated"

# Run database migrations
print_header "Step 5: Running Database Migrations"
npx prisma migrate deploy
print_success "Database migrations completed"

# Seed default data
print_header "Step 6: Seeding Default Data"

# Create seed script inline
cat > .temp-seed.ts << 'EOF'
import { PrismaClient } from '@prisma/client'
import { hash } from 'argon2'

const prisma = new PrismaClient()

async function seed() {
    // Create default tenant
    const tenant = await prisma.tenant.upsert({
        where: { slug: 'default' },
        update: {},
        create: {
            name: 'Default Organization',
            slug: 'default',
            isActive: true,
        },
    })

    // Create admin user
    const adminPassword = process.env.ADMIN_PASSWORD || 'admin123'
    const hashedPassword = await hash(adminPassword)

    const admin = await prisma.user.upsert({
        where: { email: 'admin@example.com' },
        update: {},
        create: {
            email: 'admin@example.com',
            password: hashedPassword,
            name: 'System Administrator',
            tenantId: tenant.id,
            isActive: true,
        },
    })

    // Create admin role
    const adminRole = await prisma.role.upsert({
        where: {
            tenantId_name: {
                tenantId: tenant.id,
                name: 'admin'
            }
        },
        update: {},
        create: {
            name: 'admin',
            description: 'Full system access',
            tenantId: tenant.id,
        },
    })

    // Create permissions
    const permissions = [
        { resource: 'users', action: 'create' },
        { resource: 'users', action: 'read' },
        { resource: 'users', action: 'update' },
        { resource: 'users', action: 'delete' },
        { resource: 'roles', action: 'manage' },
        { resource: 'admin', action: 'read' },
        { resource: 'admin', action: 'write' },
    ]

    for (const perm of permissions) {
        const permission = await prisma.permission.upsert({
            where: {
                tenantId_resource_action: {
                    tenantId: tenant.id,
                    resource: perm.resource,
                    action: perm.action,
                },
            },
            update: {},
            create: {
                resource: perm.resource,
                action: perm.action,
                tenantId: tenant.id,
            },
        })

        await prisma.rolePermission.upsert({
            where: {
                roleId_permissionId: {
                    roleId: adminRole.id,
                    permissionId: permission.id,
                },
            },
            update: {},
            create: {
                roleId: adminRole.id,
                permissionId: permission.id,
            },
        })
    }

    // Assign admin role to admin user
    await prisma.userRole.upsert({
        where: {
            userId_roleId: {
                userId: admin.id,
                roleId: adminRole.id,
            },
        },
        update: {},
        create: {
            userId: admin.id,
            roleId: adminRole.id,
        },
    })

    // Create default tenant plan
    await prisma.tenantPlan.upsert({
        where: { tenantId: tenant.id },
        update: {},
        create: {
            tenantId: tenant.id,
            planType: 'starter',
            rateLimit: 100,
            maxUsers: 10,
            maxStorage: 1073741824, // 1GB
            isActive: true,
        },
    })

    console.log('✓ Default data seeded successfully')
}

seed()
    .catch((e) => {
        console.error('Seeding failed:', e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
EOF

npx tsx --env-file=.env .temp-seed.ts
rm .temp-seed.ts
print_success "Default data seeded"

# Build the application
print_header "Step 7: Building Application"
npm run build
print_success "Application built"

# Start the backend service
print_header "Step 8: Starting Backend Service"
docker-compose up -d backend
print_success "Backend service started"

# Wait for backend to be healthy
print_info "Waiting for backend to be ready..."
sleep 5

MAX_RETRIES=30
RETRY=0
until curl -f http://localhost:3000/health > /dev/null 2>&1 || [ $RETRY -eq $MAX_RETRIES ]; do
    print_info "Waiting for backend... ($RETRY/$MAX_RETRIES)"
    RETRY=$((RETRY+1))
    sleep 2
done

if [ $RETRY -eq $MAX_RETRIES ]; then
    print_warning "Backend health check timed out (it may still be starting)"
else
    print_success "Backend is healthy"
fi

# ─── Setup Complete ───────────────────────────────────────────

print_header "🎉 Setup Complete!"

echo ""
echo -e "${GREEN}Your Enterprise SaaS Backend is ready!${NC}"
echo ""
echo "📍 Services:"
echo "   • API Server:    http://localhost:3000"
echo "   • API Docs:      http://localhost:3000/docs"
echo "   • Health Check:  http://localhost:3000/health"
echo "   • PostgreSQL:    localhost:5432"
echo "   • Redis:         localhost:6379"
echo ""

if [ -f .setup-credentials.txt ]; then
    echo "🔐 Credentials:"
    cat .setup-credentials.txt | grep -A 20 "Admin User:"
    echo ""
    echo -e "${YELLOW}⚠ Important: Your credentials are saved in .setup-credentials.txt${NC}"
    echo -e "${YELLOW}  Please store them securely and delete the file!${NC}"
    echo ""
fi

echo "📚 Next Steps:"
echo "   1. Test the API: curl http://localhost:3000/health"
echo "   2. View docs: open http://localhost:3000/docs"
echo "   3. Login with admin credentials above"
echo "   4. Read the documentation in docs/ folder"
echo ""
echo "🛠️  Useful Commands:"
echo "   • View logs:        docker-compose logs -f backend"
echo "   • Stop services:    docker-compose down"
echo "   • Restart:          docker-compose restart backend"
echo "   • Database CLI:     docker-compose exec postgres psql -U postgres -d enterprise_saas"
echo "   • Redis CLI:        docker-compose exec redis redis-cli"
echo ""
echo -e "${GREEN}Happy coding! 🚀${NC}"
echo ""
